# Numpy

In [5]:
import numpy as np

Нафига он нужен?

In [1]:
x = [1, 2, 3]
y = [3, 4, 8]
x + y

[1, 2, 3, 3, 4, 8]

In [2]:
3*x

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
sum(x)

6

In [4]:
type(x)

list

In [6]:
x = np.array([1, 2, 3])
y = np.array([3, 4, 8])
x + y

array([ 4,  6, 11])

In [7]:
3*x

array([3, 6, 9])

In [8]:
type(x)

numpy.ndarray

In [9]:
x@y

35

In [10]:
np.dot(x,y)

35

А ещё numpy быстрее работает!

In [11]:
x = np.arange(10**7)
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = list(x)
y[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
%%timeit
sum(y)

990 ms ± 34.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%%timeit
np.sum(x)

6.58 ms ± 292 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Функционал! 

## Задача 1

Реализуйте функцию, возвращающую максимальный элемент в векторе `x` среди элементов, перед которыми стоит нулевой.

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать None.

In [21]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0, 2, 0])

In [17]:
x.max() # не то, что я хочу :(

7

In [19]:
x == 0  # векторное сравнение

array([False, False,  True, False,  True,  True, False, False,  True,
       False,  True])

In [20]:
y = [6, 2, 0, 3, 0, 0, 5, 7, 0]
y == 0 # лист работает не так, как я ожидаю :(

False

In [23]:
x > 2

array([ True, False, False,  True, False, False,  True,  True, False,
       False, False])

In [24]:
x[x > 2] # срез только тех элементов, где было True

array([6, 3, 5, 7])

In [29]:
x.shape

(11,)

In [30]:
x.size

11

In [40]:
usl = (x == 0)
usl = usl[:(x.size - 1)]
usl

array([False, False,  True, False,  True,  True, False, False,  True,
       False])

In [50]:
x[1:][usl]

array([3, 0, 5, 2])

In [43]:
x[1:][usl].max()

5

In [46]:
# могу записать решение в 1 строку
x[1:][(x == 0)[:(x.size - 1)]].max()

5

__Матрицы__

In [195]:
A = np.array([[1,2,3],[5,9,12],[55,4,18]])
A

array([[ 1,  2,  3],
       [ 5,  9, 12],
       [55,  4, 18]])

In [196]:
A.shape

(3, 3)

In [197]:
A.size

9

In [198]:
np.linalg.det(A)

-171.00000000000009

In [199]:
np.linalg.matrix_rank(A)

3

In [200]:
np.diag(A).sum() #trace - след

28

In [201]:
np.linalg.eig(A) # собственные значения и вектора

(array([28.96988035, -2.96240849,  1.99252814]),
 array([[ 0.12782715,  0.23315039, -0.09320857],
        [ 0.53415947,  0.63839869, -0.84238555],
        [ 0.83566374, -0.73354482,  0.53075299]]))

$$
A \cdot x = b
$$


In [202]:
A

array([[ 1,  2,  3],
       [ 5,  9, 12],
       [55,  4, 18]])

In [203]:
b = np.array([2, 3, 4])

In [204]:
x = np.linalg.solve(A,b)
x

array([-0.84210526, -4.15789474,  3.71929825])

In [205]:
A@x # матричное умножение

array([2., 3., 4.])

In [206]:
np.dot(A, x)

array([2., 3., 4.])

In [207]:
B = np.linalg.inv(A) # обратная матрица
B

array([[-0.66666667,  0.14035088,  0.01754386],
       [-3.33333333,  0.85964912, -0.01754386],
       [ 2.77777778, -0.61988304,  0.00584795]])

In [208]:
A@B

array([[ 1.00000000e+00,  1.11022302e-16, -1.73472348e-18],
       [ 5.32907052e-15,  1.00000000e+00, -6.93889390e-18],
       [ 8.88178420e-16,  6.66133815e-16,  1.00000000e+00]])

In [209]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [210]:
np.sum(np.abs(np.eye(3) - A@B)) < 1e-14

True

In [212]:
np.allclose(np.eye(3), A@B)

True

__Разные умножения__

In [73]:
A

array([[ 1,  2,  3],
       [ 5,  9, 12],
       [55,  4, 18]])

In [76]:
B = np.random.normal(size=(3,3))
B

array([[-0.34748726,  1.29566299,  0.57780287],
       [ 1.56522227, -0.55551529,  1.70546858],
       [ 1.10621666,  0.34792433,  0.71281168]])

In [77]:
A @ B # матричное умножение

array([[ 6.10160726,  1.22840539,  6.12717508],
       [25.62416403,  5.65376925, 26.79197178],
       [ 7.06098948, 75.30204096, 51.43164221]])

In [78]:
A * B # поэлементное умножение

array([[-0.34748726,  2.59132597,  1.7334086 ],
       [ 7.82611134, -4.99963762, 20.46562301],
       [60.84191636,  1.39169731, 12.83061029]])

__Самое полезное:__

In [91]:
A

array([[ 1,  2,  3],
       [ 5,  9, 12],
       [55,  4, 18]])

In [92]:
A.sum() # сумма всех элементов из матрицы

109

In [93]:
A.sum(axis=0) # все строки складываются друг с другом

array([61, 15, 33])

In [94]:
A.sum(axis=1)

array([ 6, 26, 77])

In [102]:
B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [103]:
np.hstack((A,B))

array([[ 1.,  2.,  3.,  1.,  1.],
       [ 5.,  9., 12.,  1.,  1.],
       [55.,  4., 18.,  1.,  1.]])

In [104]:
B.T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np.vstack((A,B.T))

array([[ 1.,  2.,  3.],
       [ 5.,  9., 12.],
       [55.,  4., 18.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [107]:
z = np.array([4, 5, 8, 10])
z

array([ 4,  5,  8, 10])

In [108]:
z.shape

(4,)

In [109]:
z.T

array([ 4,  5,  8, 10])

In [110]:
z.T.shape

(4,)

In [119]:
z = z.reshape((1, 4))
z

array([[ 4,  5,  8, 10]])

In [120]:
z.shape

(1, 4)

In [117]:
z.T

array([[ 4],
       [ 5],
       [ 8],
       [10]])

In [118]:
z.T.shape

(4, 1)

In [121]:
A 

array([[ 1,  2,  3],
       [ 5,  9, 12],
       [55,  4, 18]])

In [124]:
A[A <= 4] = 0
A

array([[ 0,  0,  0],
       [ 5,  9, 12],
       [55,  0, 18]])

In [128]:
B = np.ones((2,2,2,2))
B

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [130]:
B.sum(axis=3)

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [170]:
A

array([[ 0,  0,  0],
       [ 5,  9, 12],
       [55,  0, 18]])

In [169]:
A[1]

array([ 5,  9, 12])

In [171]:
A[:,1]

array([0, 9, 0])

In [172]:
A[1,1]

9

## Задача 2

Есть матрица $X$. Нужно отнормировать её столбцы к отрезку $[0;1]$:

$$
x^{*}=\frac{x−min(x)}{max(x)−min(x)}
$$

In [147]:
B = np.random.normal(size=(4,3))
B

array([[-0.23799488,  0.41448801,  0.56562901],
       [-0.06649212,  0.19817525, -0.54147984],
       [ 0.00298974, -0.42572133,  0.92881104],
       [-1.34885643,  0.02180006,  0.78940099]])

In [137]:
B.min()

-1.5168566970861226

In [138]:
B - B.min()

array([[0.        , 0.41838118, 1.57436458],
       [1.87127061, 3.03674189, 2.17818942],
       [0.93994328, 0.84808073, 3.01292782],
       [1.9769832 , 1.54591849, 2.31368145]])

In [150]:
# укахание axis = 0 говорит по какой размерности взаимодействовать
B.min(axis=0)

array([-1.34885643, -0.42572133, -0.54147984])

In [148]:
B

array([[-0.23799488,  0.41448801,  0.56562901],
       [-0.06649212,  0.19817525, -0.54147984],
       [ 0.00298974, -0.42572133,  0.92881104],
       [-1.34885643,  0.02180006,  0.78940099]])

In [149]:
B - B.min(axis=0)

array([[1.11086155, 0.84020933, 1.10710885],
       [1.28236431, 0.62389657, 0.        ],
       [1.35184617, 0.        , 1.47029087],
       [0.        , 0.44752138, 1.33088083]])

In [152]:
B1 = (B - B.min(axis=0)) / (B.max(axis=0) - B.min(axis=0))
B1

array([[0.82173665, 1.        , 0.75298628],
       [0.94860224, 0.74254897, 0.        ],
       [1.        , 0.        , 1.        ],
       [0.        , 0.53263081, 0.905182  ]])

Часто надо считать расстояния! 

In [153]:
print((50 - 75) ** 2)
print((1 - 1.5) ** 2)

(50 - 75) ** 2 + (1 - 1.5) ** 2

625
0.25


625.25

In [156]:
B = np.array([[50, 1], [75,  1.5], [80, 1.8]])
B1 = (B - B.min(axis=0)) / (B.max(axis=0) - B.min(axis=0))
B1

array([[0.        , 0.        ],
       [0.83333333, 0.625     ],
       [1.        , 1.        ]])

## Задача 3

Реализуйте функцию, принимающую на вход матрицу $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент матрицы.

In [157]:
X = np.random.normal(size=(4,3))
X

array([[-2.38445609, -1.17081583, -1.28616479],
       [-2.19892222,  0.85522626,  0.51274567],
       [-0.28848934,  0.71697339, -0.27443558],
       [-1.59178986,  0.66514472,  1.13983816]])

In [158]:
a = 0.4

In [161]:
np.abs(X - a).min()

0.1127456744477835

In [167]:
R = np.abs(X - a)
R == R.min()
X[R == R.min()][0]

0.5127456744477835

In [177]:
np.argmin(np.abs(X - a))

5

In [178]:
R = np.abs(X - a)
np.where(R == R.min()) # достает массив из индексов, которые True

(array([1]), array([2]))

In [179]:
X[np.where(R == R.min())]

array([0.51274567])

## Задание 4:

Усложним предыдущую задачу! Дана матриц $X$ и вектор $v$. Нужно найти в матрице $X$ строку, которая будет ближе всего к вектору $v$.


In [190]:
X = np.random.normal(size=(5,2))
X

array([[-0.20615741, -1.00373137],
       [-0.69377008,  1.58946381],
       [ 0.24117421,  0.45787693],
       [-0.77038238,  1.04646372],
       [-0.43483477, -0.19956505]])

In [191]:
v = np.array([-0.1, 0.5])

$$
\rho_2(x,y)= \sum_{i=1}^n (x_i - y_i)^2
$$

In [194]:
indx = np.argmin(np.sum((X - v)**2, axis=1))
indx

2

In [193]:
X[indx]

array([0.24117421, 0.45787693])

In [ ]:
np.allclose()