<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Решаем-задачи" data-toc-modified-id="Решаем-задачи-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Решаем задачи</a></span><ul class="toc-item"><li><span><a href="#Задачи-с-семинара" data-toc-modified-id="Задачи-с-семинара-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Задачи с семинара</a></span><ul class="toc-item"><li><span><a href="#A" data-toc-modified-id="A-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>A</a></span></li><li><span><a href="#B" data-toc-modified-id="B-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>B</a></span></li><li><span><a href="#C" data-toc-modified-id="C-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>C</a></span></li><li><span><a href="#D" data-toc-modified-id="D-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>D</a></span></li></ul></li><li><span><a href="#Задачи-с-контеста" data-toc-modified-id="Задачи-с-контеста-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Задачи с контеста</a></span><ul class="toc-item"><li><span><a href="#A" data-toc-modified-id="A-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>A</a></span></li><li><span><a href="#B" data-toc-modified-id="B-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>B</a></span></li><li><span><a href="#C" data-toc-modified-id="C-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>C</a></span></li><li><span><a href="#D" data-toc-modified-id="D-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>D</a></span></li><li><span><a href="#i(lya)" data-toc-modified-id="i(lya)-1.2.5"><span class="toc-item-num">1.2.5&nbsp;&nbsp;</span>i(lya)</a></span></li><li><span><a href="#E" data-toc-modified-id="E-1.2.6"><span class="toc-item-num">1.2.6&nbsp;&nbsp;</span>E</a></span></li></ul></li></ul></li></ul></div>

# Решаем задачи

В будущем вы будете учить анализ данных. Там неожиданно выяснится, что любые данные - это матрица. Там-то вы и увидите впервые всю мощь numpy. 

## Задачи с семинара

In [1]:
import numpy as np

### A

Реализуйте функцию, возвращающую максимальный элемент в векторе $x$ среди элементов, перед которыми стоит нулевой. 

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать `None`.

In [2]:
# Тут должен появиться ваш код
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x

array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [3]:
zero_mask = x==0
zero_mask

array([False, False,  True, False,  True,  True, False, False,  True])

In [4]:
x[zero_mask]

array([0, 0, 0, 0])

In [5]:
x[1:][zero_mask]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 8 but corresponding boolean dimension is 9

In [6]:
zero_mask[:-1]

array([False, False,  True, False,  True,  True, False, False])

In [7]:
x[1:][zero_mask[:-1]]

array([3, 0, 5])

In [8]:
np.max(x[1:][zero_mask[:-1]])

5

In [9]:
np.max(x[1:][(x==0)[:-1]])

5

In [10]:
y=[]
for i in range(len(x)-1):
    if x[i] == 0:
        y.append(x[i+1])
max(y)

5

__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем? Можно же использовать цикл!". Да, можно. Но векторные вычисления работают на порядок быстрее. Часто сделать их намного удобнее, чем написать цикл.

### B

Есть матрица $X$. Нужно отнормировать её столбцы к отрезку $[0;1]:$

$$
x^{*} = \frac{x−min(x)}{max(x)−min(x)}
$$

In [11]:
# Тут должен появиться ваш код

__Зачем?__ 

К вам в голову тут должна была прийти мысль: "Зачем вообще делать это?". 

Обычно в машинном обучении по строчкам записывают наблюдения, по столбцам разные признаки. Часто между объектами надо считать расстояния. Представим, что у нас в выборке два наблюдения. Петя, который весит $50$ кг при росте $1$ метр. И Вася, который вести $75$ кг при росте в $1.5$ метра. То есть Петя описывается вектором $(50, 1)$, а Вася $(75, 1.5)$. 

Если нам надо вычислить между парнями расстояние, мы будем делать это так:

In [12]:
print((50 - 75) ** 2)
print((1 - 1.5) ** 2)
(50 - 75) ** 2 + (1 - 1.5) ** 2

625
0.25


625.25

Намного больше внимания уделяется весу. Чтобы такого не возникало, надо отнормировать все признаки к одной шкале. Например, отрезку $[0;1]$. 

> Если хотите узнать о том как линал используется в машинном обучении больше, смотрите небольшой видос про рекомендательные системы ["От матрицы до больших данных"](https://www.youtube.com/watch?v=Or119IXozCM)

In [13]:
A = np.random.normal(loc=10, scale=20, size=(10,2))
A

array([[ 16.07325656, -22.7440394 ],
       [ 29.85056617,  26.46673564],
       [-16.90729302,  20.53992559],
       [-13.28568007,  55.0808449 ],
       [  9.62728055,  11.59104509],
       [ -4.27369288, -18.65179728],
       [  0.6685228 ,  41.84832384],
       [ -9.11114524,  30.22979786],
       [-30.83617946,  -6.78378467],
       [  6.57437127,  15.96371561]])

In [14]:
A.shape

(10, 2)

In [15]:
minn = A.min(axis=0)
maxx = A.max(axis=0)

In [16]:
minn

array([-30.83617946, -22.7440394 ])

In [17]:
maxx

array([29.85056617, 55.0808449 ])

In [18]:
minn.shape

(2,)

In [19]:
A-minn

array([[46.90943601,  0.        ],
       [60.68674562, 49.21077504],
       [13.92888644, 43.28396499],
       [17.55049939, 77.8248843 ],
       [40.46346001, 34.3350845 ],
       [26.56248658,  4.09224213],
       [31.50470226, 64.59236324],
       [21.72503422, 52.97383727],
       [ 0.        , 15.96025474],
       [37.41055072, 38.70775502]])

In [20]:
(A-minn)/(maxx-minn)

array([[0.77297663, 0.        ],
       [1.        , 0.63232699],
       [0.22952106, 0.55617127],
       [0.28919823, 1.        ],
       [0.66675943, 0.44118388],
       [0.43769832, 0.05258269],
       [0.51913646, 0.82997057],
       [0.35798648, 0.68067994],
       [0.        , 0.20507907],
       [0.6164534 , 0.4973699 ]])

### C

Реализуйте функцию, принимающую на вход матрицу $X$ и некоторое число $a$ и возвращающую ближайший к числу элемент матрицы. А потом перепишите её так, чтобы она возвращала самый дальний элемент. 

In [21]:
# Тут должен появиться ваш код
import numpy as np


In [22]:
X = np.random.poisson(lam=5, size=(2,5))
X

array([[8, 2, 6, 3, 4],
       [5, 5, 2, 6, 3]])

In [23]:
a = 0

In [24]:
index = np.abs(a-X).argmin()
X.ravel()[index]

2

In [25]:
X.ravel()[np.abs(a-X).argmax()]

8

In [26]:
X.ravel()

array([8, 2, 6, 3, 4, 5, 5, 2, 6, 3])

In [27]:
X.reshape(1,-1)[0,:]

array([8, 2, 6, 3, 4, 5, 5, 2, 6, 3])

In [28]:
X.reshape(1,-1)[0,np.abs(a-X).argmax()]

8

### D

Усложним предыдущую задачу! Дана матрица $X$ и вектор $v$. Нужно найти в матрице $X$ строку, которая будет ближе всего к вектору $v$. 

In [29]:
# Тут должен появиться ваш код

In [30]:
X = np.random.poisson(lam=5, size=(10,5))
X

array([[ 5,  1,  7,  7,  4],
       [ 4,  7,  5,  5,  6],
       [ 5,  9,  4,  2,  4],
       [ 5,  8, 11,  6,  2],
       [ 9,  7,  6,  3,  2],
       [ 1,  6,  1, 12,  5],
       [ 2,  5,  7,  9,  6],
       [ 4,  3,  3,  9,  5],
       [ 2,  2, 11,  5,  1],
       [ 4,  5,  6,  5,  6]])

In [31]:
v = np.random.poisson(lam=5, size=5)
v

array([2, 9, 7, 3, 4])

In [32]:
np.abs(X-v).sum(axis=1).argmin()

2

__Зачем?__ 

Зачем вообще кому-то нужны задания 3 и 4?! В машинном обучения всюду вектора! Например, есть волшебная технология __word2vec__. В ней все слова превращают в вектора так, чтобы в них был закодирован смысл слова. В итоге неожиданно оказывается, что эти вектора можно складывать и вычитать. Если взять вектор _король_, вычесть из него _мужчина_ и добавить _женщина_, внезапно получится вектор, самым близким к которому является _королева_. 

Все эти вычисления удобно делать в `numpy`, написанными нами функциями. Поиграться с такой моделью и калькулятором слов можно [на сайте resvectores](https://rusvectores.org/ru/calculator/#)

## Задачи с контеста

- Задачи из [необязательного контеста](https://official.contest.yandex.ru/contest/25960/enter/)
- вас ждут простые и не очень задачи на numpy

### A

In [33]:
import numpy as np


x = np.array(list(map(float, input().split(" "))))
y = np.array(list(map(float, input().split(" "))))


print(1 if np.array_equal(x,y) else 0)

1 2 3
0 0 0
0


In [34]:
x

array([1., 2., 3.])

In [35]:
y

array([0., 0., 0.])

### B

In [36]:
import numpy as np

n = int(input())
print(np.arange(1,n**2+1).reshape(n,n).diagonal().sum())

5
65


In [37]:
np.arange(1,n**2+1).reshape(n,n)#.diagonal().sum()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### C

In [38]:
x = np.array(list((map(float, input().split()))))

1 2 0 0 4 0


In [39]:
print(np.where(x!=0)[0].sum())

5


### D

In [40]:
x = np.array(list((map(int, input().split()))))

1 -5 3


In [41]:
x

array([ 1, -5,  3])

In [42]:
np.zeros_like(x)

array([0, 0, 0])

In [43]:
np.array([x,np.zeros_like(x)])

array([[ 1, -5,  3],
       [ 0,  0,  0]])

In [44]:
np.vstack((x, np.zeros_like(x))).T

array([[ 1,  0],
       [-5,  0],
       [ 3,  0]])

In [45]:
print(*np.vstack((x, np.zeros_like(x))).T.ravel()[:-1])

1 0 -5 0 3


### i(lya)

- найти первые элементы ступенчатой матрицы

In [46]:
s = '''100500 10 1 15 1
0 0 228 222 2
0 0 0 0 333'''

In [47]:
X = np.array([list(map(int,x.split())) for x in s.split('\n')])
X

array([[100500,     10,      1,     15,      1],
       [     0,      0,    228,    222,      2],
       [     0,      0,      0,      0,    333]])

In [48]:
[X[i,np.where(X[i]!=0)[0][0]] for i in range(X.shape[0])]

[100500, 228, 333]

In [49]:
[np.where(X[i]!=0)[0][0] for i in range(X.shape[0])]

[0, 2, 4]

In [50]:
print(*[X[i,np.where(X[i]!=0)[0][0]] for i in range(X.shape[0])])

100500 228 333


### E

- для задачи нужно создать txt-файл в папке Downloads через jupyter как на скриншоте
- код ниже прочитает файл оттуда и работа будет с ним

<a href="https://imgbb.com/"><img src="https://i.ibb.co/MG571X3/Screen-Shot-2021-03-25-at-21-47-13.png" alt="Screen-Shot-2021-03-25-at-21-47-13" border="0"></a>

In [62]:
import numpy as np
file = open('/Users/UOUR_USERNAME/Downloads/input.txt','r') 
data = file.readlines()


n,m = list(map(int,data[0].split()))
X = np.array([list(map(int,x.split())) for x in data[1:]])


In [63]:
n,m

(4, 3)

In [64]:
X

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

In [65]:

if all(X.diagonal()==0):
    print(-1)
else:
    print(np.prod(np.where(X.diagonal()==0,1,X.diagonal())))

3
