# Numpy

In [1]:
import numpy as np

## 1. А нафига её написали? 

In [3]:
a = [1, 2, 3]
b = [4, 5, 8]
type(a)

list

In [4]:
a + b

[1, 2, 3, 4, 5, 8]

In [5]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 8])
type(a)

numpy.ndarray

In [7]:
a

array([1, 2, 3])

In [8]:
a + b

array([ 5,  7, 11])

In [9]:
3*a

array([3, 6, 9])

In [10]:
a@b # матричное умножение (для векторов скалярное <a,b> )

38

In [11]:
np.dot(a, b)

38

In [12]:
x = np.arange(10**7)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [14]:
y = list(x)
y[-10:]

[9999990,
 9999991,
 9999992,
 9999993,
 9999994,
 9999995,
 9999996,
 9999997,
 9999998,
 9999999]

In [18]:
%%timeit
np.sum(x)

5.95 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%%timeit
sum(y)

957 ms ± 61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
957/6

159.5

## 2. Функционал!

In [25]:
x = np.array([1, -2, 3, -4, 5])
x

array([ 1, -2,  3, -4,  5])

In [35]:
x.shape

(5,)

In [37]:
x.size

5

In [26]:
x[3]

-4

In [27]:
x[3:]

array([-4,  5])

In [28]:
x > 0  # маска 

array([ True, False,  True, False,  True])

In [29]:
x[x > 0] # оставил только те элементы, где было True

array([1, 3, 5])

In [42]:
A = np.array([[22, 42, 52 ], [3, 5, 2], [-5, 8, 11]])
A

array([[22, 42, 52],
       [ 3,  5,  2],
       [-5,  8, 11]])

In [43]:
A.shape

(3, 3)

In [44]:
A.size

9

In [45]:
A[2,2]

11

In [46]:
A[2] # строка матрицы

array([-5,  8, 11])

In [47]:
A[:,2] # столбец из матрицы

array([52,  2, 11])

In [48]:
A >= 5

array([[ True,  True,  True],
       [False,  True, False],
       [False,  True,  True]])

In [49]:
A[A >= 5]

array([22, 42, 52,  5,  8, 11])

In [50]:
A[A < 5] = 0
A

array([[22, 42, 52],
       [ 0,  5,  0],
       [ 0,  8, 11]])

In [51]:
A[1,1] = 55
A

array([[22, 42, 52],
       [ 0, 55,  0],
       [ 0,  8, 11]])

In [52]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
B = np.ones((2,2,2))
B.shape

(2, 2, 2)

In [55]:
B

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [56]:
A

array([[22, 42, 52],
       [ 0, 55,  0],
       [ 0,  8, 11]])

In [60]:
B = np.random.normal(size=(3,2))
B

array([[ 0.22528351, -0.70519469],
       [-1.6001748 , -2.3887157 ],
       [ 0.10059617,  1.15363118]])

In [61]:
A@B

array([[ -57.02010321,  -55.85152138],
       [ -88.00961377, -131.37936355],
       [ -11.69484047,   -6.41978265]])

In [62]:
np.dot(A, B)

array([[ -57.02010321,  -55.85152138],
       [ -88.00961377, -131.37936355],
       [ -11.69484047,   -6.41978265]])

In [63]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [64]:
np.hstack((A,B))

array([[22.        , 42.        , 52.        ,  0.22528351, -0.70519469],
       [ 0.        , 55.        ,  0.        , -1.6001748 , -2.3887157 ],
       [ 0.        ,  8.        , 11.        ,  0.10059617,  1.15363118]])

In [65]:
np.vstack((A,B))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [66]:
B.T

array([[ 0.22528351, -1.6001748 ,  0.10059617],
       [-0.70519469, -2.3887157 ,  1.15363118]])

In [67]:
np.vstack((A,B.T))

array([[22.        , 42.        , 52.        ],
       [ 0.        , 55.        ,  0.        ],
       [ 0.        ,  8.        , 11.        ],
       [ 0.22528351, -1.6001748 ,  0.10059617],
       [-0.70519469, -2.3887157 ,  1.15363118]])

In [68]:
np.linalg.det(A) # определитель

13309.999999999996

In [69]:
np.linalg.eig(A) 

(array([22., 11., 55.]),
 array([[ 1.        , -0.9783497 ,  0.83773195],
        [ 0.        ,  0.        ,  0.53727332],
        [ 0.        ,  0.20695859,  0.09768606]]))

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
D = np.linalg.inv(A)
D

array([[ 0.04545455, -0.00345605, -0.21487603],
       [ 0.        ,  0.01818182,  0.        ],
       [ 0.        , -0.01322314,  0.09090909]])

In [73]:
A@D

array([[ 1.00000000e+00,  1.38777878e-17, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -3.46944695e-18,  1.00000000e+00]])

In [78]:
np.abs(A@D - np.eye(3)).sum() < 1e-15

True

In [79]:
np.allclose(A@D, np.eye(3))

True

$$
Ax = b
$$

In [80]:
A

array([[22, 42, 52],
       [ 0, 55,  0],
       [ 0,  8, 11]])

In [82]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [84]:
x = np.linalg.solve(A,b) # можно решать системы уравнений
x

array([-0.60608565,  0.03636364,  0.24628099])

In [85]:
A@x

array([1., 2., 3.])

Про оси и размерности

In [87]:
A

array([[22, 42, 52],
       [ 0, 55,  0],
       [ 0,  8, 11]])

In [88]:
A.sum()

190

In [89]:
np.sum(A)

190

In [ ]:
# kartoshka - объект

# kartoshka.pojarit( ) # метод 
# pojarit(kartoshka)   # функция

In [90]:
A.sum(axis = 0)

array([ 22, 105,  63])

In [91]:
A.sum(axis = 1)

array([116,  55,  19])

In [92]:
A.min(axis = 0)

array([0, 8, 0])

In [94]:
B = np.ones((2,2,2))
B

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [95]:
B.sum(axis=2)

array([[2., 2.],
       [2., 2.]])

In [96]:
B = np.ones((2,2,3))
B

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [97]:
B.reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
B.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

## 3. Решаем задачки

__Задача 1__ 

Реализуйте функцию, возвращающую максимальный элемент в векторе $x$ среди элементов, перед которыми стоит нулевой.

Например, для `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])` ответом является `5`. Если нулевых элементов нет, функция должна возвращать `None`.

In [108]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0, 2])
x

array([6, 2, 0, 3, 0, 0, 5, 7, 0, 2])

In [109]:
x == 0

array([False, False,  True, False,  True,  True, False, False,  True,
       False])

In [103]:
x[x==0]

array([0, 0, 0, 0, 0])

In [111]:
usl = (x == 0)
usl = usl[:-1]
x[1:][usl].max()

5

__Задача 2__

Матрица $X$. Нужно пронормировать данные к отрезку $[0;1]$ по столбцам

$$
x^{*} = \frac{x - min(x)}{max(x) - min(x)}
$$

In [122]:
X = np.random.normal(size=(3,4))
X

array([[-1.41534036,  0.35771296, -0.52278721, -0.97676897],
       [ 0.6998203 ,  1.02144426, -0.61824606,  0.950492  ],
       [ 0.37482438, -0.72640536, -0.21560176,  1.05755967]])

In [129]:
X.min(axis = 0)

array([-1.41534036, -0.72640536, -0.61824606, -0.97676897])

In [130]:
X

array([[-1.41534036,  0.35771296, -0.52278721, -0.97676897],
       [ 0.6998203 ,  1.02144426, -0.61824606,  0.950492  ],
       [ 0.37482438, -0.72640536, -0.21560176,  1.05755967]])

In [128]:
X_scaled = (X - X.min(axis = 0)) / (X.max(axis = 0) - X.min(axis = 0)) 
X_scaled

array([[0.        , 0.62025835, 0.23707985, 0.        ],
       [1.        , 1.        , 0.        , 0.94736953],
       [0.8463493 , 0.        , 1.        , 1.        ]])

А если я хочу вычитать по столбикам? 

In [131]:
X.min(axis = 1)

array([-1.41534036, -0.61824606, -0.72640536])

In [134]:
X - X.min(axis = 1)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [138]:
(X.T - X.min(axis = 1)).T  # первый выход

array([[0.        , 1.77305332, 0.89255315, 0.43857139],
       [1.31806636, 1.63969032, 0.        , 1.56873806],
       [1.10122974, 0.        , 0.51080359, 1.78396502]])

In [141]:
X - X.min(axis = 1).reshape(3,1) # вычитать вектор столбец - альтернативный выход

array([[0.        , 1.77305332, 0.89255315, 0.43857139],
       [1.31806636, 1.63969032, 0.        , 1.56873806],
       [1.10122974, 0.        , 0.51080359, 1.78396502]])

In [145]:
m = X.min(axis = 1)
m

array([-1.41534036, -0.61824606, -0.72640536])

In [147]:
m.shape

(3,)

In [146]:
m1 = m.reshape(3,1)
m1

array([[-1.41534036],
       [-0.61824606],
       [-0.72640536]])

In [149]:
m1.shape

(3, 1)

In [151]:
m1.T

array([[-1.41534036, -0.61824606, -0.72640536]])

In [152]:
m1.T.shape

(1, 3)

In [154]:
m[:,np.newaxis] # другой способ завести новую размерность 

array([[-1.41534036],
       [-0.61824606],
       [-0.72640536]])

In [155]:
m[:,None] # другой способ завести новую размерность 

array([[-1.41534036],
       [-0.61824606],
       [-0.72640536]])

Зачем?

In [115]:
# Миша  50  1.5
# Димма 80  2

X = np.array([[50, 1.5],  [80, 2]])
X

array([[50. ,  1.5],
       [80. ,  2. ]])

In [117]:
np.sqrt( (80 - 50)**2 + (2 - 1.5)**2 )

30.004166377354995

In [118]:
(80 - 50)**2 

900

In [119]:
(2 - 1.5)**2

0.25

Когда полезно ввести новую размерность? 

In [156]:
A = np.random.normal(size=(3,4))
B = np.random.normal(size=(3,4))
A, B

(array([[-0.55216055,  0.77752443,  0.59341913, -1.45459905],
        [ 0.7354753 , -0.0868404 , -0.49110149,  2.95375077],
        [ 1.3498797 ,  0.54575355, -1.00049248, -0.21093201]]),
 array([[-0.9467713 , -1.09054451,  1.01718848, -1.54689818],
        [ 0.83006129,  0.2261388 , -1.8118502 , -0.17912181],
        [ 1.63458922,  0.08823916, -0.6877272 ,  1.04488601]]))

Я хочу посчитать Евклидово расстояние между каждой строкой из 1 матрицы и каждой строкой из 2 матрицы.

In [158]:
A - B # не то :(

array([[ 0.39461074,  1.86806894, -0.42376935,  0.09229913],
       [-0.09458599, -0.3129792 ,  1.32074871,  3.13287258],
       [-0.28470952,  0.45751439, -0.31276527, -1.25581802]])

In [162]:
A[::,None]

array([[[-0.55216055,  0.77752443,  0.59341913, -1.45459905]],

       [[ 0.7354753 , -0.0868404 , -0.49110149,  2.95375077]],

       [[ 1.3498797 ,  0.54575355, -1.00049248, -0.21093201]]])

In [161]:
A[::,None] - B

array([[[ 0.39461074,  1.86806894, -0.42376935,  0.09229913],
        [-1.38222184,  0.55138563,  2.40526933, -1.27547724],
        [-2.18674977,  0.68928527,  1.28114634, -2.49948506]],

       [[ 1.68224659,  1.00370411, -1.50828997,  4.50064895],
        [-0.09458599, -0.3129792 ,  1.32074871,  3.13287258],
        [-0.89911393, -0.17507955,  0.19662571,  1.90886475]],

       [[ 2.296651  ,  1.63629805, -2.01768096,  1.33596617],
        [ 0.51981841,  0.31961474,  0.81135772, -0.0318102 ],
        [-0.28470952,  0.45751439, -0.31276527, -1.25581802]]])

In [169]:
np.sqrt( ((A[::,None] - B)**2).sum(axis=2) )

array([[1.95793228, 3.10269658, 3.62570686],
       [5.1349932 , 3.41557758, 2.12637838],
       [3.71590086, 1.01571552, 1.40188443]])

In [167]:
sum([-1.38222184,  0.55138563,  2.40526933, -1.27547724])

0.29895587999999984

# ....

## Profit